version: '3.8'

services:
  # MongoDB Database Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB port to the host machine for direct access if needed
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongo-data:/data/db

  # Authentication Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    env_file: ./.env # Use environment variables from the .env file
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  # Profile & Books Service
  profile-service:
    build: ./profile-service
    container_name: profile-service
    env_file: ./.env # Use environment variables from the .env file
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  # Frontend Service (served by Nginx)
  frontend:
    build: ./frontend
    container_name: frontend

  # Nginx Reverse Proxy (The main entrypoint for the app)
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8080:80" # Access the entire application at http://localhost:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - auth-service
      - profile-service

volumes:
  mongo-data: