apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: user-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: user-management-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: user-management-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: user-management-config
              key: BACKEND_PORT
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: user-management-secrets
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-management-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRE
          valueFrom:
            configMapKeyRef:
              name: user-management-config
              key: JWT_EXPIRE
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: user-management-config
              key: FRONTEND_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
