apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-config
  namespace: user-management
data:
  NODE_ENV: "production"
  BACKEND_PORT: "5000"
  FRONTEND_URL: "https://your-frontend-domain.com"
  MONGODB_DATABASE: "usermanagement"
  JWT_EXPIRE: "7d"
  VITE_API_URL: "https://your-backend-domain.com"
