apiVersion: v1
kind: Secret
metadata:
  name: user-management-secrets
  namespace: user-management
type: Opaque
data:
  # Base64 encoded values
  # Use: echo -n "your-secret" | base64
  MONGODB_ROOT_USERNAME: YWRtaW4=  # admin
  MONGODB_ROOT_PASSWORD: c2VjcmV0cGFzc3dvcmQxMjM=  # secretpassword123
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOnNlY3JldHBhc3N3b3JkMTIzQG1vbmdvZGI6MjcwMTcvdXNlcm1hbmFnZW1lbnQ/YXV0aFNvdXJjZT1hZG1pbg==
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u
